### ISSUE TITLE
What does war = devWar mean?

### ISSUE THREAD

**Issue by aterreno** [EvidentSolutions/gradle-beanstalk-plugin#1]
Hi, 
I am a bit new to the gradle/beanstalk world, so sorry if the question sounds dumb, what devWar should be? 
Do I need a plugin to get the devWar? 

thanks in advance

**Comment by komu** [comment]
Right, the documentation is a bit unclear (or basically nonexistent).

`devWar` is a task that produces the war-file that you want to deploy. So you could have something like the following in the build-file:

``` groovy
task devWar(type: War, dependsOn: classes) {
    baseName = 'my-dev-war'
    webInf { from 'src/additionalWebInf' }
    classpath fileTree('additionalLibs') /
}
```

If you don't have any custom war-files, you can replace `devWar` with `tasks.war`, which will point to the default war created by the war-plugin:

``` groovy
deployments {
    production {
        war = tasks.war
        ...
    }
}
```

Since this is probably the most common setup, I'll update the example in documentation to this. This also probably makes it clearer that `war` can point to a task. (It would also be possible to say `war = tasks.devWar` instead of `war = devWar`.)

If you wish, you can also point to directly to a file on the filesystem:

``` groovy
deployments {
    production {
        war = file('my-app.war')
        ...
    }
}
```

However, pointing directly to a task is usually more convenient, because Gradle will then automatically add a dependency from the deployment-task to the given war-task.

Did this make any sense?

**Comment by aterreno** [comment]
Nice, thanks for the prompt reply!
