### ISSUE TITLE
rename `war` to `file`

### ISSUE THREAD

**Issue by musketyr** [EvidentSolutions/gradle-beanstalk-plugin#11]
Currently you can specify `war` property to specify file being uploaded as new version to Beanstalk but any file can be used. It would make more sense if the configuration property is called `file` or `archive`

**Comment by msgilligan** [comment]
Thanks for this, was wondering whether this plugin would work with a *Ratpack* JAR...

**Comment by musketyr** [comment]
@msgilligan  I've just dropped a line how to pack a Ratpack or anything else and deploy to Beanstalk https://medium.com/@musketyr/how-to-deploy-java-application-jar-to-aws-beanstalk-with-gradle-35343337febf

**Comment by komu** [comment]
This sounds like a good idea to implement. The problem is that I have not been using Beanstalk for a while and don't even have a testing environment configured right now. I'm a little hesitant making even straightforward changes like this without any testing.

So could either of you open a PR, test your changes against Beanstalk and submit it? I could then do the release chores and publish a new version.

**Comment by musketyr** [comment]
@komu see #12

**Comment by komu** [comment]
I just published `0.1.2` with these changes. Please take it for a spin.

**Comment by musketyr** [comment]
I can't access it from the build.

Dne čt 9. 11. 2017 11:02 uživatel Juha Komulainen <notifications@github.com>
napsal:

**Comment by komu** [comment]
Yeah, seems like something weird is going on with Gradle plugin repository. 

* https://plugins.gradle.org/plugin/fi.evident.beanstalk/0.1.2 shows that the plugin is published
* https://plugins.gradle.org/m2/gradle/plugin/fi/evident/gradle/beanstalk/gradle-beanstalk-plugin/0.1.2/ lists the plugin files, but if you click any of them, you'll get 404

I tried republishing the same bits as `0.2.1+1`, but the same thing happens.

**Comment by komu** [comment]
I added #14 for tracking this.
