### ISSUE TITLE
Failed deploy returns "No Configuration Template Named"

### ISSUE THREAD

**Issue by julioomoura** [EvidentSolutions/gradle-beanstalk-plugin#25]
I'm trying to deploy my app, but the deployment always fails and returns this error:

> No Configuration Template named 'my-project/default' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 7f8d6ceb-eb84-4bb6-873a-b3bcaa1b39b4)

that's my beanstalk configuration in build.gradle

```

beanstalk {
	s3Endpoint = "s3-us-west-2.amazonaws.com"
	beanstalkEndpoint = "elasticbeanstalk.us-west-2.amazonaws.com"

	deployments {
		staging {
			file = tasks.bootJar
			application = 'myproject'
			environment = 'myproject-staging'
		}
		production {
			file = tasks.bootJar
			application = 'myproject'
			environment = "myproject-${project.version.replaceAll('\\.', '-')}"
			template = 'default' 
		}
	}
}
```

**Comment by komu** [comment]
Have you created a configuration template named like that on BeanStalk? Or if you don't want a configuration template at all, just take the ´template = 'default'` line away. The line in the README is just supposed to demonstrate how you can configure a custom template to be used if you need one.

And similarly, if you don't need separate staging and production environments, you don't need to configure both. Or if you want more environments, you can define them as well, the deployment names don't mean anything to the plugin:

```
beanstalk {
    deployments {
         staging { ... }
         demo { ... }
         production { ... }
         whateverIsNeeded { ... }
         yetAnotherDeployment { ... }
    }
}
```

**Comment by julioomoura** [comment]
When you say that: 
> Have you created a configuration template named like that on BeanStalk?
> ```

Are you refering to the name "staging"/"production" or "default"? Should I create a template named default?

**Comment by komu** [comment]
You have the line:

```
template = 'default'
```

in your configuration, but it appears that you don't have a template named `default` in BeanStalk. Therefore the error.

If you don't know what templates are or don't care about them, just delete the line. I suspect that it's only in your configuration because it's copied verbatim from the example in the README, but you don't really need it. If you actually need templates, then the problem is on BeanStalk's side.

**Comment by julioomoura** [comment]
OK.. thanks!

I tried to deploy without that line:

`template = 'default'`

And it still return that error. I suppose that's because by default the class is constructed with the parameter template set as "default"

**Comment by komu** [comment]
Ah, sorry about that. Looking at blame for readme it seems that `template` was added as part of the support for creating environments automatically if they don't exist.

So either you need to create the environment in which you plan to deploy manually (in which case the template won't be used, but environment must exist) or you can let the plugin create the environment (in which case the template for the environment must exist).

Your configuration seems to suggest that the name of the environment is created dynamically which suggests that it does not exist yet:

```groovy
environment = "myproject-${project.version.replaceAll('\\.', '-')}"
```

Then again, that is directly from the example, so perhaps that is not what you want. If you have already created an environment named `my-environment` then you can simply specify `environment = "my-environment"`. If you have not created the environment (though AWS console or command line tools), you must create the template so that the plugin can create the environment for you based on that.

**Comment by julioomoura** [comment]
Awesome, man! Thanks
