### ISSUE TITLE
Support for JDK 8

### ISSUE THREAD

**Issue by dbpatel219** [EvidentSolutions/gradle-beanstalk-plugin#32]
Wondering if there is a way to support JDK 8 version as well.   I assume JDK 8 version will work on newer versions but not vice versa.  I'm getting an exception stating the version is compiled in a newer version.

```
has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by komu** [comment]
Oh sorry. I changed my default Java from Java 8 to Java 11 a while ago and it seems there are no explicit toolchain definitions in the build-file since the project is so old. So the release got built with wrong bits.

I published [a new `0.3.2`-release](https://plugins.gradle.org/plugin/fi.evident.beanstalk) which should work with Java 8. Let me know if you have any problems.
